kind: PersistentVolume
apiVersion: v1
metadata:
  name: couchdb001-data-volume
  namespace: default
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/data1/data01"
