apiVersion: v1
kind: Service
metadata:
  labels:
    app: couchdb
  name: kubetest001
  namespace: default
spec:
  ports:
  - name: in-tcp-port
    port: 80
    targetPort: 5984
  - name: EPMD
    port: 4369
    targetPort: 4369
  - name: distributed-erlang-port
    port: 9100
    targetPort: 9100
  - name: admin-port
    port: 5986
    targetPort: 5986
  selector:
    tier: backend
    app: couchdb
    cluster: kubetest001
  type: NodePort
