apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: couchdb001
  namespace: default
spec:
  serviceName: couchdb001-backend
  replicas: 3
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
            {
            "name": "configer-couch",
            "image": "glyndwr/kube-init-couchdb",
            "command": ["/bin/bash", "-c", "/./configer_couch.sh"],
            "volumeMounts": [
                {
                    "name": "core-config",
                    "mountPath": "/core-config/"
                                  },
                {
                    "name": "pod-config-store",
                    "mountPath": "/opt/couchdb/etc/"
                                  }
                              ],
            "env": [
                {
                    "name": "INSTALL_LOCATION",
                    "value": "/opt/couchdb"
                }
                              ] 
              }
            ]'
      labels:
        cluster: couchdb001
        tier: backend
        app: couchdb
    spec:
      containers:
      - env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CLUSTER_ADM_USER
          valueFrom:
            secretKeyRef:
              name: cluster-adm
              key: username
        - name: CLUSTER_ADM_PASS
          valueFrom:
            secretKeyRef:
              name: cluster-adm
              key: password
        image: klaemo/couchdb:2.0.0
        name: couchdb
        imagePullPolicy: Always
        ports:
        - containerPort: 5984
          name: in-tcp-port
        - containerPort: 4369
          name: epmd
        - containerPort: 9100
          name: erlang-port
        - containerPort: 5986
          name: admin-port
        volumeMounts:
        - mountPath: /core-config/
          name: core-config
        - mountPath: /opt/couchdb/etc/
          name:  pod-config-store
      - name: couchdb-readiness
        image: glyndwr/kube-couchdb-readiness
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CLUSTER_ADM_USER
          valueFrom:
            secretKeyRef:
              name: cluster-adm
              key: username
        - name: CLUSTER_ADM_PASS
          valueFrom:
            secretKeyRef:
              name: cluster-adm
              key: password
        - name: INSTALL_LOCATION
          value: /opt/couchdb
        - name: NODES_DB
          value: _nodes
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - /./join_cluster.py _users
          initialDelaySeconds: 15
          timeoutSeconds: 5
      volumes:
      - name: core-config
        configMap:
          name: core-config
      - name: pod-config-store
        emptyDir: {}
